version: "2"

services:
  github-backup:
    build: .
    image: github-backup:latest
    container_name: "github-backup"
    hostname: "github-backup"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

    environment:
      - GITHUB_USER
      - TOKEN=${GITHUB_ACCESS_TOKEN}
      - MAX_BACKUPS=10
      - TIME_ZONE=America/Los_Angeles
    volumes:
      - ${PWD}:/srv/var
